# Generated by Django 5.0.6 on 2024-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(max_length=50)),
                ('number_of_dependents', models.IntegerField()),
                ('employment_type', models.CharField(choices=[('self_employed', 'Self Employed'), ('gig_worker', 'Gig Worker'), ('salaried', 'Salaried')], max_length=20)),
                ('job_role', models.CharField(max_length=100)),
                ('employer_details', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_income_sources', models.CharField(blank=True, max_length=255, null=True)),
                ('savings_group_membership', models.CharField(blank=True, max_length=255, null=True)),
                ('existing_debts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repayment_history', models.TextField(blank=True, null=True)),
                ('community_references', models.TextField(blank=True, null=True)),
                ('guarantors', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('utility_bill_history', models.TextField(blank=True, null=True)),
                ('rent_payment_history', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
