# Generated by Django 5.0.6 on 2024-05-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='rent_payment_history',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='utility_bill_history',
        ),
        migrations.AddField(
            model_name='worker',
            name='id_photo',
            field=models.ImageField(default=True, upload_to='id_photos/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('utility_bill', 'Utility Bill'), ('rent_payment', 'Rent Payment'), ('repayment', 'Repayment')], max_length=20)),
                ('file', models.FileField(upload_to='receipts/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='workerdata.worker')),
            ],
        ),
    ]
