# Generated by Django 5.0.6 on 2024-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerdata', '0002_remove_worker_rent_payment_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='repayment_history',
        ),
        migrations.AlterField(
            model_name='worker',
            name='employment_type',
            field=models.CharField(choices=[('self_employed', 'Self Employed'), ('gig_worker', 'Gig Worker'), ('salaried', 'Salaried')], max_length=13),
        ),
        migrations.AlterField(
            model_name='worker',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=8),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monthly_income',
            field=models.CharField(choices=[('0-5000', 'Ksh 0 - Ksh 5000'), ('5001-10000', 'Ksh 5001 - Ksh 10,000'), ('10001-20000', 'Ksh 10,001 - Ksh 20,000'), ('20001-30000', 'Ksh 20,001 - Ksh 30,000'), ('30001-40000', 'Ksh 30,001 - Ksh 40,000'), ('40001-50000', 'Ksh 40,001 - Ksh 50,000'), ('50001+', 'Above Ksh 50,000')], max_length=11),
        ),
    ]
